- title: "Portfolio"
  description: "El source code de este mismo portfolio. Eres libre de usarlo, si te gustó."
  technologies: 
    - Astro
    - React
    - Tailwind CSS
  github: "https://github.com/yourusername/portfolio"
  demo: "https://github.com/PsHohe/portfolio-desafio"

- title: "Pipeline en Jenkins"
  description: "Ejemplo de uso de Jenkins para realize un pipeline de integración y despliegue."
  technologies:
    - Jenkins
    - Docker
  github: "https://github.com/PsHohe/pipeline-jenkins"
  demo: null

- title: "App móvil de Certificados"
  description: "Realizada para Traumafire Capacitaciones, aplicación móvil con animaciones y presentación de credenciales virtuales."
  technologies:
    - Flutter
    - Postgresql
  appstore: "https://apps.apple.com/cl/app/6743162948"
  playstore: "https://play.google.com/store/apps/details?id=cl.salaconectada.traumafire"
  github: null
  demo: null
